# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---

Organizations:

    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/bc4scm.de/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

    - &IBO
        Name: IBOMSP
        ID: IBOMSP
        MSPDir: crypto-config/peerOrganizations/ibo.bc4scm.de/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('IBOMSP.admin', 'IBOMSP.peer', 'IBOMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('IBOMSP.admin', 'IBOMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('IBOMSP.admin')"

        AnchorPeers:
            - Host: peer0.ibo.bc4scm.de
              Port: 7051

    - &Retailer
        Name: RetailerMSP
        ID: RetailerMSP
        MSPDir: crypto-config/peerOrganizations/retailer.bc4scm.de/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('RetailerMSP.admin', 'RetailerMSP.peer', 'RetailerMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('RetailerMSP.admin', 'RetailerMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('RetailerMSP.admin')"

        AnchorPeers:
            - Host: peer0.retailer.bc4scm.de
              Port: 9051

    - &Supplier
        Name: SupplierMSP
        ID: SupplierMSP
        MSPDir: crypto-config/peerOrganizations/supplier.bc4scm.de/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('SupplierMSP.admin', 'SupplierMSP.peer', 'SupplierMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('SupplierMSP.admin', 'SupplierMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('SupplierMSP.admin')"

        AnchorPeers:
            - Host: peer0.supplier.bc4scm.de
              Port: 11051

    - &Logistic
        Name: LogisticMSP
        ID: LogisticMSP
        MSPDir: crypto-config/peerOrganizations/logistic.bc4scm.de/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('LogisticMSP.admin', 'LogisticMSP.peer', 'LogisticMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('LogisticMSP.admin', 'LogisticMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('LogisticMSP.admin')"

        AnchorPeers:
            - Host: peer0.logistic.bc4scm.de
              Port: 11051

Capabilities:
    Channel: &ChannelCapabilities
        V1_3: true

    Orderer: &OrdererCapabilities
        V1_1: true

    Application: &ApplicationCapabilities
        V1_3: true
        V1_2: false
        V1_1: false

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
        - orderer.bc4scm.de:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB

    Kafka:
        Brokers:
            - 127.0.0.1:9092

    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"


Channel: &ChannelDefaults

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities


Profiles:
    TwoOrgsOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *IBO
                    - *Retailer
                    - *Supplier
                    - *Logistic
    IBOCommonChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *IBO
                - *Retailer
                - *Supplier
                - *Logistic
            Capabilities:
                <<: *ApplicationCapabilities

    IBOCustomerChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *IBO
            Capabilities:
                <<: *ApplicationCapabilities

    IBOSupplierChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *IBO
                - *Supplier
            Capabilities:
                <<: *ApplicationCapabilities

    IBOLogisticChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *IBO
                - *Logistic
            Capabilities:
                <<: *ApplicationCapabilities
