# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

OrdererOrgs:

  - Name: Orderer
    Domain: bc4scm.de

    Specs:
      - Hostname: orderer

PeerOrgs:

  - Name: IBO
    Domain: ibo.bc4scm.de
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: Retailer
    Domain: retailer.bc4scm.de
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: Supplier
    Domain: supplier.bc4scm.de
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 2

  - Name: SupplierA
    Domain: suppliera.bc4scm.de
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 2

  - Name: SupplierB
    Domain: supplierb.bc4scm.de
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 2

  - Name: Logistic
    Domain: logistic.bc4scm.de
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
