# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer2.bc4scm.de:
  orderer3.bc4scm.de:
  orderer4.bc4scm.de:
  orderer5.bc4scm.de:

networks:
  byfn:

services:

  orderer2.bc4scm.de:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer2.bc4scm.de
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/bc4scm.de/orderers/orderer2.bc4scm.de/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/bc4scm.de/orderers/orderer2.bc4scm.de/tls/:/var/hyperledger/orderer/tls
        - orderer2.bc4scm.de:/var/hyperledger/production/orderer
    ports:
    - 8050:7050

  orderer3.bc4scm.de:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer3.bc4scm.de
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/bc4scm.de/orderers/orderer3.bc4scm.de/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/bc4scm.de/orderers/orderer3.bc4scm.de/tls/:/var/hyperledger/orderer/tls
        - orderer3.bc4scm.de:/var/hyperledger/production/orderer
    ports:
    - 9050:7050

  orderer4.bc4scm.de:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer4.bc4scm.de
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/bc4scm.de/orderers/orderer4.bc4scm.de/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/bc4scm.de/orderers/orderer4.bc4scm.de/tls/:/var/hyperledger/orderer/tls
        - orderer4.bc4scm.de:/var/hyperledger/production/orderer
    ports:
    - 10050:7050

  orderer5.bc4scm.de:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer5.bc4scm.de
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/bc4scm.de/orderers/orderer5.bc4scm.de/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/bc4scm.de/orderers/orderer5.bc4scm.de/tls/:/var/hyperledger/orderer/tls
        - orderer5.bc4scm.de:/var/hyperledger/production/orderer
    ports:
    - 11050:7050
