# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.bc4scm.de:
  peer0.ibo.bc4scm.de:
  peer1.ibo.bc4scm.de:
  peer0.retailer.bc4scm.de:
  peer1.retailer.bc4scm.de:

networks:
  byfn:

services:

  orderer.bc4scm.de:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.bc4scm.de
    container_name: orderer.bc4scm.de
    networks:
      - byfn

  peer0.ibo.bc4scm.de:
    container_name: peer0.ibo.bc4scm.de
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.ibo.bc4scm.de
    networks:
      - byfn

  peer1.ibo.bc4scm.de:
    container_name: peer1.ibo.bc4scm.de
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.ibo.bc4scm.de
    networks:
      - byfn

  peer0.retailer.bc4scm.de:
    container_name: peer0.retailer.bc4scm.de
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.retailer.bc4scm.de
    networks:
      - byfn

  peer1.retailer.bc4scm.de:
    container_name: peer1.retailer.bc4scm.de
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.retailer.bc4scm.de
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.ibo.bc4scm.de:7051
      - CORE_PEER_LOCALMSPID=IBOMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ibo.bc4scm.de/peers/peer0.ibo.bc4scm.de/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ibo.bc4scm.de/peers/peer0.ibo.bc4scm.de/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ibo.bc4scm.de/peers/peer0.ibo.bc4scm.de/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ibo.bc4scm.de/users/Admin@ibo.bc4scm.de/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.bc4scm.de
      - peer0.ibo.bc4scm.de
      - peer1.ibo.bc4scm.de
      - peer0.retailer.bc4scm.de
      - peer1.retailer.bc4scm.de
    networks:
      - byfn
