# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.bc4scm.de:
  peer0.ibo.bc4scm.de:
  peer1.ibo.bc4scm.de:
  peer0.retailer.bc4scm.de:
  peer1.retailer.bc4scm.de:

networks:
  byfn:
services:
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-ibo
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.ibo.bc4scm.de-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.ibo.bc4scm.de-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/ibo.bc4scm.de/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerIBO
    networks:
      - byfn

  ca1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-retailer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.retailer.bc4scm.de-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.retailer.bc4scm.de-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/retailer.bc4scm.de/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerRetailer
    networks:
      - byfn

  orderer.bc4scm.de:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.bc4scm.de
    container_name: orderer.bc4scm.de
    networks:
      - byfn

  peer0.ibo.bc4scm.de:
    container_name: peer0.ibo.bc4scm.de
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.ibo.bc4scm.de
    networks:
      - byfn

  peer1.ibo.bc4scm.de:
    container_name: peer1.ibo.bc4scm.de
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.ibo.bc4scm.de
    networks:
      - byfn

  peer0.retailer.bc4scm.de:
    container_name: peer0.retailer.bc4scm.de
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.retailer.bc4scm.de
    networks:
      - byfn

  peer1.retailer.bc4scm.de:
    container_name: peer1.retailer.bc4scm.de
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.retailer.bc4scm.de
    networks:
      - byfn
